### PR TITLE
Account pages

### PR DESCRIPTION
**Pull request by alexandercyu**
Pages for the user to administrate their user account

2024-08-02
-------------

Layout of account main page added

2024-08-08
-------------
Settings page added

2024-08-13
------------
Help page added

2024-09-12
------------
- Menu item colour highlighting finished
- Menu links finished
- Menu Network Node link finished

- Help page links to Support is dynamic

- Settings page error messages finished

TODO
-------
Functionality for all pages

Login Page
-----------
- Regular login placeholder added for now until cross-origin error can be worked around or testing is done on live production node
- Github provider login
- OAuth login for other providers
- 
Settings Page
--------------
- Update user details  - placeholder function made (Same situation as login function)
- Network Nodes modal (depends on future feature to be created that will allow user to access all nodes by logging into a single node)

### CODE REVIEW

**Review by ShrutiK100 — CHANGES_REQUESTED** [review]
-  The visibility icon is non-functional.

- In original Magpie UI, Edit Profile displays the masked password and email address.

Screenshot 2024-08-28 at 2 07 09 PM
We should be able to display these values in new UI as well. 

- What is the functionality of back button here? 

- I recommend to replace it with delete button that deletes the entire account

**Comment by alexandercyu** [comment]
> * The visibility icon is non-functional.
> 
>     * In original Magpie UI, Edit Profile displays the masked password and email address.
> 
> 

>     * What is the functionality of back button here?
> 
>     * I recommend to replace it with delete button that deletes the entire account



We discussed these points with Steve on August 8

> * The visibility icon is non-functional.
>     * In original Magpie UI, Edit Profile displays the masked password and email address.

The original Magpie UI does not display the masked password.  There is no connection between the stars you see in the original Magpie UI and the password.  

Steve and I have both said putting the password in the page is a security hole.


>     * What is the functionality of back button here?


From the August 8 meeting, the back button replaced the reset button that was originally there.  Because we agreed the password was not going to be put into the page there was no need for a reset button.  Steve also said the user can go back a page using the browser back button.  The back button here is just to make that point clear to the user.  

I had originally wanted to back button to go back to the previous page the user had been on, but that may cause unintended issues.  Perhaps it will be better to make this a Back to Home button and force the user to go to Account Home?

>     * I recommend to replace it with delete button that deletes the entire account

I asked you during the August 8 meeting about moving the Delete button from where it currently is and you said it didn't fit with common UI designs.

So you now want the delete button on the left?

**Comment by ShrutiK100** [comment]
> We discussed these points with Steve on August 8
> 
> > * The visibility icon is non-functional.
> >   
> >   * In original Magpie UI, Edit Profile displays the masked password and email address.
> 
> The original Magpie UI does not display the masked password. There is no connection between the stars you see in the original Magpie UI and the password.
I understand that we cannot display password, although we should add stars as text as represented in Magpie UI
> 
> Steve and I have both said putting the password in the page is a security hole.
> 
> > ```
> > * What is the functionality of back button here?
> > ```
> 
> From the August 8 meeting, the back button replaced the reset button that was originally there. Because we agreed the password was not going to be put into the page there was no need for a reset button. Steve also said the user can go back a page using the browser back button. The back button here is just to make that point clear to the user.

The user can navigate to previous page or go back through top tab navigator, thus it is best replace the reset button button delete button instead of back button
> 
> I had originally wanted to back button to go back to the previous page the user had been on, but that may cause unintended issues. Perhaps it will be better to make this a Back to Home button and force the user to go to Account Home?
To avoid confusion and unintented issues it's best to remove the back button. 
> 
> > ```
> > * I recommend to replace it with delete button that deletes the entire account
> > ```
> 
> I asked you during the August 8 meeting about moving the Delete button from where it currently is and you said it didn't fit with common UI designs.
When we discussed this there were 2 buttons already present in the form, you were proposing to add thrid button(delete button) to the form that would disrupt the standard design. Standard form design must consist of 2 buttons only. Removal of back button eliminates user confusion and provides with space for a second button(Delete Button).
Changes have been made in the figma design. 
> 
> Do you now want the delete button on the left?

**Comment by alexandercyu** [comment]
> I understand that we cannot display password, although we should add stars as text as represented in Magpie UI

Since the title for this field says "New Password" I don't think there should be anything in the field.  It sends the wrong message to the user. I see you also removed the eye icon/visibility toggle.  Is the visibility function removed from the password field?  What if the user was entering a new password in a public area?  This would be a step back in security.

**Review by ShrutiK100 — CHANGES_REQUESTED** [review]
Screenshot 2024-09-10 at 11 24 48 AM
Add Title : Username
Subtitle: "Name of the user", add xyz for now

Figma : Screenshot 2024-09-10 at 11 26 12 AM

Screenshot 2024-09-10 at 11 29 06 AM
Maintain the gap between each section of the form : 30px.

Screenshot 2024-09-10 at 11 30 06 AM

Screenshot 2024-09-10 at 11 34 22 AM
Network Node pop up background colour is black with 51% opacity. Add effect background blur 15%
Shadow behind is black with 18% opacity.
Figma:
Screenshot 2024-09-10 at 11 35 22 AM
Screenshot 2024-09-10 at 11 38 16 AM
Remove extending white background 
Screenshot 2024-09-10 at 11 38 16 AM

Text is not aligned in a row.
Screenshot 2024-09-10 at 11 47 01 AM

**Comment by alexandercyu** [comment]
Add Title : Username Subtitle: "Name of the user", add xyz for now
> 
> Figma : Screenshot 2024-09-10 at 11 26 12 AM
> 

The figma shows Username is Subtitle1

Screenshot 2024-09-10 at 12 28 26 PM

**Comment by alexandercyu** [comment]
Remove extending white background Screenshot 2024-09-10 at 11 38 16 AM
> 


Could this be the bottom scrollbar?

Screenshot 2024-09-10 at 1 02 39 PM (2)

**Comment by alexandercyu** [comment]
Screenshot 2024-09-10 at 11 34 22 AM Network Node pop up background colour is black with 51% opacity. Add effect background blur 15% Shadow behind is black with 18% opacity. Figma: Screenshot 2024-09-10 at 11 35 22 AM 


Figma shows background of black with 18% opacity and backdrop filter of 7.5px blur:

Screenshot 2024-09-10 at 1 30 32 PM (2)


Which is already applied:

Screenshot 2024-09-10 at 1 28 51 PM (2)

**Comment by ShrutiK100** [comment]
> Screenshot 2024-09-10 at 11 24 48 AM Add Title : Username Subtitle: "Name of the user", add xyz for now
> Figma : Screenshot 2024-09-10 at 11 26 12 AM
> 
> Screenshot 2024-09-10 at 11 29 06 AM Maintain the gap between each section of the form : 30px. Screenshot 2024-09-10 at 11 30 06 AM Screenshot 2024-09-10 at 11 34 22 AM Network Node pop up background colour is black with 51% opacity. Add effect background blur 15% Shadow behind is black with 18% opacity. Figma: Screenshot 2024-09-10 at 11 35 22 AM Screenshot 2024-09-10 at 11 38 16 AM Remove extending white background Screenshot 2024-09-10 at 11 38 16 AM
> Text is not aligned in a row. Screenshot 2024-09-10 at 11 47 01 AM

The UI does not match with the Figma UI . In order to build an identical design we need to make adjustments and see what works.

**Comment by alexandercyu** [comment]
>  Add Title : Username Subtitle: "Name of the user", add xyz for now
- Added placeholder username "XYZ"
- Made Username heading Subtitle-1, username text body-1

> Maintain the gap between each section of the form : 30px.

- spacing between form elements made 30px



> Network Node pop up background colour is black with 51% opacity. Add effect background blur 15% Shadow behind is black with 18% opacity. 

- Background colour and blur adjusted


> Remove extending white background 
- Removed bottom scrollbar
- Border radius fixed for Safari

> Text is not aligned in a row. 
- Adjusted width of columns in network node table

**Review by ShrutiK100 — CHANGES_REQUESTED** [review]
Nav Bar is fixed at the top although Close button isn't.
The header text is overlapping the table contents, solution to this could be to display a table header with a white background while scrolling.
Will make design chnages in figma which you can refer to.

**Comment by alexandercyu** [comment]
> Nav Bar is fixed at the top although Close button isn't. The header text is overlapping the table contents, solution to this could be to display a table header with a white background on while scrolling through table content. Will make design changes in figma which you can refer to.

- Close button now fixed at top
- Added white opacity background to header when scrolling

**Comment by alexandercyu** [comment]
- Made header stick to top when scrolling
- Added border radius to header when scrolling
- Fixed delete button icon showing on top of header when scrolling
- Fixed network node entries wrapping in safari
- Fixed extra white X close button appearing when  close button changes to black

**Comment by alexandercyu** [comment]
Fixed error in menu for pages that don't have modals to open.

**Review by ShrutiK100 — APPROVED** [review]

**Pull request merged**
