### PR TITLE
Marble Login User Interface

### PR DESCRIPTION
**Pull request by alexandercyu**
This is the page that allows a user to log in to a node.  It provides input for a username and password, or the use of a provider for authentication.

TODO
------

The functional programming for logging in, getting provider details, and getting the current node's contact email

### CODE REVIEW

**Review by ShrutiK100 — CHANGES_REQUESTED** [review]
The shadow above login section is missing. Adjusting y value should help.
Screenshot 2024-07-19 at 11 10 07 AM
Email id is missing
Screenshot 2024-07-19 at 11 13 54 AM

For the record wrong email or wrong password entered should be display in as a message under the text input boxes.

**Comment by alexandercyu** [comment]
> The shadow above login section is missing. Adjusting y value should help. Screenshot 2024-07-19 at 11 10 07 AM


The shadow settings from figma caused a box to appear around the image.  I worked with you on this on Tuesday and finalized the new shadow settings.  Here is the original shadow:

Screenshot 2024-07-19 at 12 59 37 PM (2)







> Email id is missing Screenshot 2024-07-19 at 11 13 54 AM
> 
> For the record wrong email or wrong password entered should be display in as a message under the text input boxes.

I said on Tuesday that the email is the current node's email.  It will depend on the current node that is running the login.  Therefore when it's not running on a node, such as now, there will be no email displayed.

I also mentioned on Tuesday that the error message is a work in progress.

**Comment by ShrutiK100** [comment]
> > The shadow above login section is missing. Adjusting y value should help. Screenshot 2024-07-19 at 11 10 07 AM
> 
> The shadow settings from figma caused a box to appear around the image. I worked with you on this on Tuesday and finalized the new shadow settings. Here is the original shadow:
> 
> Screenshot 2024-07-19 at 12 59 37 PM (2)
> 
> > Email id is missing Screenshot 2024-07-19 at 11 13 54 AM
> > For the record wrong email or wrong password entered should be display in as a message under the text input boxes.
> 
> I said on Tuesday that the email is the current node's email. It will depend on the current node that is running the login. Therefore when it's not running on a node, such as now, there will be no email displayed.
> 
> I also mentioned on Tuesday that the error message is a work in progress.

Just mentioning it here since these issues were not raised on Github. Good to have it on record so we don't miss on any changes

**Comment by alexandercyu** [comment]
> > > The shadow above login section is missing. Adjusting y value should help. Screenshot 2024-07-19 at 11 10 07 AM
> > 
> > 
> > The shadow settings from figma caused a box to appear around the image. I worked with you on this on Tuesday and finalized the new shadow settings. Here is the original shadow:
> > Screenshot 2024-07-19 at 12 59 37 PM (2)
> > > Email id is missing Screenshot 2024-07-19 at 11 13 54 AM
> > > For the record wrong email or wrong password entered should be display in as a message under the text input boxes.
> > 
> > 
> > I said on Tuesday that the email is the current node's email. It will depend on the current node that is running the login. Therefore when it's not running on a node, such as now, there will be no email displayed.
> > I also mentioned on Tuesday that the error message is a work in progress.
> 
> Just mentioning it here since these issues were not raised on Github. Good to have it on record so we don't miss on any changes

Does this mean the box shadow and the email are fine?

**Comment by alexandercyu** [comment]
Screenshot 2024-07-19 at 6 36 23 PM (2)

I got the email on the reset password working.  If you have a login for the U of T node you'll see this as well.

**Comment by alexandercyu** [comment]
Screenshot 2024-07-23 at 6 22 32 PM (2)
Screenshot 2024-07-23 at 6 22 08 PM (2)

Got the node contact email for the error message and the reset password modal displayed. This works for both cases when the user is logged in and not logged in.

**Comment by ShrutiK100** [comment]
> Screenshot 2024-07-23 at 6 22 32 PM (2) Screenshot 2024-07-23 at 6 22 08 PM (2)
> 
> Got the node contact email for the error message and the reset password modal displayed. This works for both cases when the user is logged in and not logged in.

I don't have an account to check the password error message. I am able to see the forgot password email now.
Unable to see box shadow above and the image behind the select provider button.

**Review by ShrutiK100 — CHANGES_REQUESTED** [review]
Screenshot 2024-07-25 at 12 43 54 PM
We need to find and link the terms and conditions

**Comment by ShrutiK100** [comment]
Screenshot 2024-07-25 at 12 46 29 PM

**Comment by alexandercyu** [comment]
> Screenshot 2024-07-25 at 12 46 29 PM

We have already discussed the top box shadow:

> > The shadow settings from figma caused a box to appear around the image. I worked with you on this on Tuesday and finalized the new shadow settings. Here is the original shadow:
> > Screenshot 2024-07-19 at 12 59 37 PM (2)

**Comment by alexandercyu** [comment]
> Screenshot 2024-07-25 at 12 46 29 PM

Misha said the password rules may not be able to be enforced, so I've removed them for now.

**Comment by alexandercyu** [comment]
> Screenshot 2024-07-25 at 12 46 29 PM

You'll have to take me through the steps of how the image is missing.  It's showing for me.

Screenshot 2024-07-25 at 2 03 41 PM (3)

**Comment by ShrutiK100** [comment]
Screenshot 2024-07-25 at 3 28 58 PM
DKRZ logo is blacked out

**Comment by alexandercyu** [comment]
> Screenshot 2024-07-25 at 3 28 58 PM DKRZ logo is blacked out

It's fine for me.

Screenshot 2024-07-25 at 3 32 32 PM (3)

**Comment by alexandercyu** [comment]
> Screenshot 2024-07-25 at 12 46 29 PM

I changed the box shadow from the containing div to the individual left and right divs as per the design.  The box shadow settings from figma are still causing a gap on the left and top of the image.

Screenshot 2024-07-26 at 3 21 53 PM (2)

**Comment by alexandercyu** [comment]
The image chosen has a transparency around the entire image.  This is why there  is gap when the box shadow is applied.
Screenshot 2024-07-26 at 3 48 45 PM (2)

**Review by ShrutiK100 — CHANGES_REQUESTED** [review]
Screenshot 2024-08-29 at 2 21 31 PM

**Comment by alexandercyu** [comment]
> Screenshot 2024-08-29 at 2 21 31 PM

- Labels for email/username and password fields added back in.
- Tooltip for password removed

**Review by ShrutiK100 — CHANGES_REQUESTED** [review]
Everything ooks good! Just one elment needs to be removed.
Screenshot 2024-09-06 at 1 34 46 PM

Since user is not entering any value in Provider Name, info dialogue needs to be removed.

**Comment by alexandercyu** [comment]
> Everything ooks good! Just one elment needs to be removed. Screenshot 2024-09-06 at 1 34 46 PM
> 
> Since user is not entering any value in Provider Name, info dialogue needs to be removed.

Removed the tooltip

**Review by ShrutiK100 — APPROVED** [review]
Looks good!

**Pull request merged**
